colorScheme = "slate"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = false
mainSections = [""] # Changed to an empty array. We'll define content structure explicitly.
robots = "all"
disableImageZoom = false
disableImageOptimization = false
disableTextInHeader = false
defaultBackgroundImage = "/img/background.jpg"  # Commented out.
defaultFeaturedImage = "/img/featured.jpg"  # Commented out.
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true

[header]
  layout = "fixed"  # Changed to "basic".  Experiment with "fixed" later.

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false # From config.toml
  showAppearanceSwitcher = false  # Disabled for now.
  showScrollToTop = true

[homepage]
  layout = "bavkground"  # Consistent with config.toml.
  homepageImage = "/img/background.jpg"  # Commented out. We'll set this in content/_index.md.
  showRecent = false
  showRecentItems = 10
  showMoreLink = false # consistant
  showMoreLinkDest = "blog"
  cardView = false  # Disabled.
  cardViewScreenWidth = false
  layoutBackgroundBlur = true

[article]
  showDate = true
  showViews = false  # Disabled.
  showLikes = false  # Disabled.
  showDateUpdated = false
  showAuthor = false
  showHero = true
  heroStyle = "thumbAndBackground"
  layoutBackgroundBlur = true
  showBreadcrumbs = false
  showDraftLabel = false
  showEdit = false
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = false  # Disabled.
  showTableOfContents = true
  showRelatedContent = false  # Disabled.
  relatedContentLimit = 6
  showTaxonomies = false  # Disabled.
  showAuthorsBadges = false
  showWordCount = false  # Disabled.
  sharingLinks = [ "linkedin", "twitter", "reddit", "whatsapp", "telegram", "pinterest", "facebook", "email"]
  showZenMode = true

[list]
  showHero = true
  heroStyle = "thumbAndBackground"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = false
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  showCards = true
  groupByYear = false
  cardView = false
  cardViewScreenWidth = true
  constrainItemsWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = false
  showHero = true
  heroStyle = "thumbAndBackground"
  showBreadcrumbs = false
  showViews = false #consistant
  showLikes = false #consistant
  showTableOfContents = true
  cardView = true

[term]
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = false
  showViews = false # consistant
  showLikes = false #consistant
  showTableOfContents = false
  groupByYear = false
  cardView = true
  cardViewScreenWidth = true

# [firebase] # Commented out.

# [fathomAnalytics] # Commented out.

# [buymeacoffee] # Commented out.

# [verification] # Commented out.