colorScheme = "slate"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = false
mainSections = ["projects"]
robots = "all"
disableImageZoom = false
disableImageOptimization = false
disableTextInHeader = false
defaultBackgroundImage = "/img/background.jpg"
defaultFeaturedImage = "/img/featured.jpg"
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true

[header]
  layout = "fixed-fill-blur"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background"
  homepageImage = "/img/background.jpg"
  showRecent = false
  showRecentItems = 10
  showMoreLink = true
  showMoreLinkDest = "true"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true

[article]
  showDate = true
  showViews = true
  showLikes = true
  showDateUpdated = false
  showAuthor = false
  showHero = true
  heroStyle = "thumbAndBackground"
  layoutBackgroundBlur = true
  showBreadcrumbs = false
  showDraftLabel = false
  showEdit = false
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 6
  showTaxonomies = true
  showAuthorsBadges = false
  showWordCount = true
  sharingLinks = [ "linkedin", "twitter", "reddit", "whatsapp", "telegram", "pinterest", "facebook", "email"]
  showZenMode = true

[list]
  showHero = true
  heroStyle = "thumbAndBackground" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = false
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  showCards = true
  groupByYear = false
  cardView = false
  cardViewScreenWidth = true
  constrainItemsWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = false
  showHero = true
  heroStyle = "thumbAndBackground" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = true
  showLikes = true
  showTableOfContents = true
  cardView = true

[term]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = true
  showLikes = true
  showTableOfContents = false
  groupByYear = false
  cardView = true
  cardViewScreenWidth = true
  
[firebase]
#  apiKey = "AIzaSyBKzZOSp_-jkFTOJDFnztYqMHi0xwuOUE8"
#  authDomain = "sicmmec.firebaseapp.com"
#  projectId = "sicmmec"
#  storageBucket = "sicmmec.appspot.com"
#  messagingSenderId = "571758868644"
#  appId = "1:571758868644:web:3d1b956b232ad5f8d98e31"
#  measurementId = "G-EL80M7VTMV"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[buymeacoffee]
   identifier = "nunocoracao"
   globalWidget = true
   globalWidgetMessage = ""
   globalWidgetColor = "#FFDD00"
   globalWidgetPosition = "Right"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""